### ISSUE TITLE
Tracking Issue: Make gh-actions nicer

### ISSUE THREAD

**Issue by tdittr** [tweedegolf/drive-rs#10]
- [ ] Add a check job that verifies entries in `driver-db` can actually be parsed and exist on crates.io
- [ ] Cache build output of Rust backend
- [ ] Cache build output of Svelte frontend
- [ ] Make jobs independent from each other (Backend, Frontend, driver-db)
